:- discontiguous agent_/2.
:- discontiguous agricultural_service/3.
:- discontiguous alice_employer/3.
:- discontiguous alice_household_maintenance/4.
:- discontiguous american_employer_/1.
:- discontiguous amount_/2.
:- discontiguous attending_classes_/1.
:- discontiguous beneficiary_/2.
:- discontiguous birth_/1.
:- discontiguous blindness_/1.
:- discontiguous brother_/1.
:- discontiguous business_/1.
:- discontiguous business_trust_/1.
:- discontiguous citizenship_/1.
:- discontiguous country_/2.
:- discontiguous daughter_/1.
:- discontiguous death_/1.
:- discontiguous deduction_/1.
:- discontiguous destination_/2.
:- discontiguous disability_/1.
:- discontiguous educational_institution_/1.
:- discontiguous end_/2.
:- discontiguous enrollment_/1.
:- discontiguous father_/1.
:- discontiguous first_day_year/2.
:- discontiguous gross_income/3.
:- discontiguous hospital_/1.
:- discontiguous incarceration_/1.
:- discontiguous income_/1.
:- discontiguous international_organization_/1.
:- discontiguous is_before/2.
:- discontiguous itemize_deductions_/1.
:- discontiguous joint_return_/1.
:- discontiguous last_day_year/2.
:- discontiguous legal_separation_/1.
:- discontiguous location_/2.
:- discontiguous marriage_/1.
:- discontiguous means_/2.
:- discontiguous medical_institution_/1.
:- discontiguous medical_patient_/1.
:- discontiguous migration_/1.
:- discontiguous mother_/1.
:- discontiguous nonresident_alien_/1.
:- discontiguous nurses_training_school_/1.
:- discontiguous patient/2.
:- discontiguous patient_/2.
:- discontiguous payment_/1.
:- discontiguous penal_institution_/1.
:- discontiguous plan_/1.
:- discontiguous purpose_/2.
:- discontiguous reason_/2.
:- discontiguous residence_/1.
:- discontiguous retirement_/1.
:- discontiguous service_/1.
:- discontiguous sibling_/1.
:- discontiguous sister_/1.
:- discontiguous son_/1.
:- discontiguous start_/2.
:- discontiguous termination_/1.
:- discontiguous type_/2.
:- discontiguous unemployment_compensation_agreement_/1.
